### ISSUE TITLE
Incorrect DD_KUBERNETES_KUBELET_HOST field path for EKS

### ISSUE THREAD

**Issue by jjshanks** [DataDog/the-monitor#95]
Per https://github.com/DataDog/integrations-core/issues/2582#issuecomment-470860868

```
- name: DD_KUBERNETES_KUBELET_HOST
           valueFrom:
             fieldRef:
               fieldPath: status.hostIP
```
needs to be replaced with
```
- name: DD_KUBERNETES_KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
```
